Repository ViNasc/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#4 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação
